spring:
  application:
    name: eiduca
  profiles:
    active: ${PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
apiPrefix: /api/v1